### ISSUE TITLE
Create a Kanban Board

### ISSUE THREAD

**Issue by petushka1** [Theophileaseh/Doctor-Appointment-Back-end#20]
# Setup and Assignment
- [x] Setup repo  
- [x] Set up Kanban Board 

![image](https://user-images.githubusercontent.com/44860643/201080111-8b392330-8be6-43bc-a2f3-49803ca4dca7.png)

### List of Member

- [Shaheer](https://github.com/ShaheerCH)
- [Basit](https://github.com/BasitKorede)
- [Nadya](https://github.com/petushka1)
- [Cecilia](https://github.com/c3c1l1a)
- [Nwachan](https://github.com/Theophileaseh)

[Kanban Board](https://github.com/users/Theophileaseh/projects/1)

**Comment by Meltrust** [comment]
Hi @petushka1

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



### To highlight:

- All cards have been pointed✔️ 

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Required Changes ♻️

- [ ] Some cards haven't been assigned to any team member:

![image](https://user-images.githubusercontent.com/57421823/201087731-b58b2f32-acfc-424f-aedd-2633a59762f8.png)

All the cards need to have an assignee.  Kindly add the assignees for those cards.

Kindly remember that the points assignations need to remain fear.  No team member should be assigned =>5 points than the others.



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Meltrust** [comment]
Hi @petushka1,


## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- The remaining cards have been assigned to a teemate✔️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
